keyvault_rg            = ""
keyvault_name          = ""
azure_region           = "westeurope"
resource_group         = "RG-AKSCluster-FPA"
cluster_name           = ""
dns_name               = ""
sku-controlplane       = "Free"
admin_username         = ""
windows_admin_username = ""
kubernetes_version     = "1.21.1"
aks_vnet_name          = ""
LogsWorkspaceName      = ""
enable-privatecluster  = false
enable-AzurePolicy     = false
networkpolicy_plugin   = "azure"
"